title: A gradient optimization toolbox for general purpose time-optimal MRI gradient waveform design
author: Michael Loecher
logo: images/gropt_logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

execute:
  execute_notebooks: 'off'

only_build_toc_files: true 

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/executablebooks/jupyter-book  
  branch: main  

html:
  favicon: images/gropt_icon.ico
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface        : "jupyterlab"  
  binderhub_url             : "https://mybinder.org"
  thebe                     : true  